# Font colors, styles and sizes
BACKGROUND_COLOR = "#1F1F23"
SIDE_BAR_COLOR = "#3C3C44"
INNER_TEXT_COLOR = "black"
DARK_BLUE = "#1F6AA5"
GREEN = "green"
GREEN_HOVER_COLOR = "#003300"
RED = "red"
RED_HOVER_COLOR = "yellow"
KEYBOARD_FONT = ("Arial", 14)
WORD_FONT = ("Arial", 24)

# Window, frame and button sizes
WIDTH = 800
HEIGHT = 300
BUTTON_CORNER_RADIUS = 10
BUTTON_HEIGHT = 60
BORDER_WIDTH = 3

# Word properties
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
MIN_WORD_LENGTH = 9
NUMBER_OF_LIVES = 8
EASY_MIN_LENGTH = 3
EASY_MAX_LENGTH = 5
MEDIUM_MIN_LENGTH = 6
MEDIUM_MAX_LENGTH = 8
HARD_MIN_LENGTH = 9
ALL_MIN_LENGTH = 3
